GEMINI_API_KEY = "AIzaSyAOjeiV6iAznAhU6BsQY1-WWEYhi4khq1E"
SUPABASE_URL = "https://eqnjqqldybqxpodjtidg.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbmpxcWxkeWJxeHBvZGp0aWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5ODc2NDAsImV4cCI6MjA5MDU2MzY0MH0.CMPxje204A4SVbcaP2eQUUCL_TOICM2ToOLcrg_FIzk"
[supabase]
url = "https://eqnjqqldybqxpodjtidg.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbmpxcWxkeWJxeHBvZGp0aWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5ODc2NDAsImV4cCI6MjA5MDU2MzY0MH0.CMPxje204A4SVbcaP2eQUUCL_TOICM2ToOLcrg_FIzk"
[db]
host     = "db.eqnjqqldybqxpodjtidg.supabase.co"
name     = "postgres"
user     = "postgres"
password = "Agitactt123."
port     = 5432